version: '2'
services:
  app:
    restart: always
    build:
      context: ./.docker
      dockerfile: Dockerfile.app
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - ${DOCKER_APP_PORT}:80
      - ${DOCKER_SOCKET_PORT}:3000
    volumes:
      - ${DOCKER_SRC}:/var/www/html
    depends_on:
      - db
  db:
    restart: always
    build:
      context: ./.docker
      dockerfile: Dockerfile.database
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${DOCKER_PG_PORT}:5432
    volumes:
      - .database:/var/lib/postgresql/data
